### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by makasim** [Payum/PayumServer#33]
- History
- ~~Take gateway from payment not a token~~
- Store gateway config inside payment.
- ~~docker container~~

Bugs:
- ~~Default gateway (not implemented)~~
- ~~Snippet~~
- ~~choose payment~~
- ~~Gateway delete~~
- ~~StoreExtension is not registered. Fixed but not best way.~~

**Comment by xros** [comment]
Many parmas to you! Thanks to you for your generous work making our payment methods easier.

Xros
