### ISSUE TITLE
Docker image doesn't work

### ISSUE THREAD

**Issue by ylt** [Payum/PayumServer#56]
Attempts to use this image result in
```<b>Fatal error</b>:  Cannot use lexical variable $value as a parameter name in <b>/payum/vendor/makasim/values/src/functions/values.php</b> on line <b>223</b><br>```.

Looking at the makasim/values project I can see that this bug has been fixed: https://github.com/makasim/values/commit/ef2306f5c7d23b75624750e3a9aaaa5623df87b0

```
joe@itchy:~/compose/payum$ docker-compose exec payum php --version
PHP 7.1.8-2+ubuntu16.04.1+deb.sury.org+4 (cli) (built: Aug  4 2017 13:04:12) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8-2+ubuntu16.04.1+deb.sury.org+4, Copyright (c) 1999-2017, by Zend Technologies

**Comment by makasim** [comment]
I've updated the `makasim/values` version up to `0.2.5`. The latest docker image or `travis-401` contains the change.
